Repository SC-ECE/WEB-PROJECT, pull requests merged in 2023-01, with the labels that each got.

#2 demo site
  demo/.gitignore
  demo/README.md
  demo/package-lock.json
  demo/package.json
  demo/public/favicon.ico
  demo/public/index.html
  demo/public/logo192.png
  demo/public/logo512.png
  demo/public/manifest.json
  demo/public/robots.txt
  demo/src/App.css
  demo/src/App.js
  demo/src/App.test.js
  demo/src/index.css
  demo/src/index.js
  demo/src/logo.svg
  demo/src/reportWebVitals.js
  demo/src/setupTests.js
Labels: Easy, Synapse

#4 1st-commit
  Portfolio-Website/README.md
  Portfolio-Website/Soham.png
  Portfolio-Website/assests/Git.png
  Portfolio-Website/assests/PostgreSQL.png
  Portfolio-Website/assests/WhatsApp Image 2021-12-12 at 6.11.04 PM.jpeg
  Portfolio-Website/assests/back-edit-1.0.png
  Portfolio-Website/assests/back-profile.png
  Portfolio-Website/assests/blob.svg
  Portfolio-Website/assests/bootstrap-logo.png
  Portfolio-Website/assests/certificates/aws.png
  Portfolio-Website/assests/certificates/c++course.png
  Portfolio-Website/assests/certificates/web dev.png
  Portfolio-Website/assests/edit-profile-1.0.jpg
  Portfolio-Website/assests/favicon/circlepic.ico
  Portfolio-Website/assests/favicon/site.webmanifest
  Portfolio-Website/assests/heroku.png
  Portfolio-Website/assests/netlify.svg
  Portfolio-Website/assests/pdfs/My Resume.pdf
  Portfolio-Website/assests/pdfs/My Resume.svg
  Portfolio-Website/assests/profilepic-soham.jpg
  Portfolio-Website/assests/soham-profile-pic.jpg
  Portfolio-Website/css/main.css
  Portfolio-Website/index.html
  Portfolio-Website/js/main.js
Labels: enhancement, Synapse

#7 Web-project created
  Payment-Form/Images/Screenshot_20230102_191127.png
  Payment-Form/Images/Screenshot_20230102_191147.png
  Payment-Form/Images/Soumyajit.png
  Payment-Form/README.md
  Payment-Form/index.html
  Payment-Form/style_form.css
Labels: Easy, Synapse

#5 Portfolio Website_Ankit_Kumar
  Portfolio_website_Ankit_Kumar/1555704980721.jpeg
  Portfolio_website_Ankit_Kumar/1597758079894.jpeg
  Portfolio_website_Ankit_Kumar/1635397111226.jpeg
  Portfolio_website_Ankit_Kumar/AOT.png
  Portfolio_website_Ankit_Kumar/Covid 19 Vaccine Information website (1).png
  Portfolio_website_Ankit_Kumar/Covid 19 Vaccine Information website (2).png
  Portfolio_website_Ankit_Kumar/Covid 19 Vaccine Information website.png
  Portfolio_website_Ankit_Kumar/How-to-type-faster-Tips-and-Tricks-to-be-a-Typing-Pro.png
  Portfolio_website_Ankit_Kumar/My photo.jpg
  Portfolio_website_Ankit_Kumar/Readme.md
  Portfolio_website_Ankit_Kumar/Script.js
  Portfolio_website_Ankit_Kumar/Style.css
  Portfolio_website_Ankit_Kumar/curl-cover-picture.png
  Portfolio_website_Ankit_Kumar/curl.webp
  Portfolio_website_Ankit_Kumar/download.jpeg
  Portfolio_website_Ankit_Kumar/download.png
  Portfolio_website_Ankit_Kumar/index.html
  Portfolio_website_Ankit_Kumar/nocrop-1.png
  Portfolio_website_Ankit_Kumar/round-gradient-designify (2).png
  Portfolio_website_Ankit_Kumar/undraw_Coding_re_iv62.png
  Portfolio_website_Ankit_Kumar/undraw_Delivery_address_re_cjca.png
  Typing speed chacker/Readme.md
  Typing speed chacker/index.html
  Typing speed chacker/script.js
  Typing speed chacker/typing.css
Labels: Medium, Synapse

#11 Typing Speed Chacker
  Portfolio_website_Ankit_Kumar/1555704980721.jpeg
  Portfolio_website_Ankit_Kumar/1597758079894.jpeg
  Portfolio_website_Ankit_Kumar/1635397111226.jpeg
  Portfolio_website_Ankit_Kumar/AOT.png
  Portfolio_website_Ankit_Kumar/Covid 19 Vaccine Information website (1).png
  Portfolio_website_Ankit_Kumar/Covid 19 Vaccine Information website (2).png
  Portfolio_website_Ankit_Kumar/Covid 19 Vaccine Information website.png
  Portfolio_website_Ankit_Kumar/How-to-type-faster-Tips-and-Tricks-to-be-a-Typing-Pro.png
  Portfolio_website_Ankit_Kumar/My photo.jpg
  Portfolio_website_Ankit_Kumar/Readme.md
  Portfolio_website_Ankit_Kumar/Script.js
  Portfolio_website_Ankit_Kumar/Style.css
  Portfolio_website_Ankit_Kumar/curl-cover-picture.png
  Portfolio_website_Ankit_Kumar/curl.webp
  Portfolio_website_Ankit_Kumar/download.jpeg
  Portfolio_website_Ankit_Kumar/download.png
  Portfolio_website_Ankit_Kumar/index.html
  Portfolio_website_Ankit_Kumar/nocrop-1.png
  Portfolio_website_Ankit_Kumar/round-gradient-designify (2).png
  Portfolio_website_Ankit_Kumar/undraw_Coding_re_iv62.png
  Portfolio_website_Ankit_Kumar/undraw_Delivery_address_re_cjca.png
  Typing speed chacker/Readme.md
  Typing speed chacker/index.html
  Typing speed chacker/script.js
  Typing speed chacker/typing.css
Labels: Medium, Synapse

#12 chess game update
  CHESS GAME/Bbishop.png
  CHESS GAME/Bking.png
  CHESS GAME/Bknight.png
  CHESS GAME/Bpawn.png
  CHESS GAME/Bqueen.png
  CHESS GAME/Brook.png
  CHESS GAME/Chess.css
  CHESS GAME/Chess.js
  CHESS GAME/README.md
  CHESS GAME/Wbishop.png
  CHESS GAME/Wking.png
  CHESS GAME/Wknight.png
  CHESS GAME/Wpawn.png
  CHESS GAME/Wqueen.png
  CHESS GAME/Wrook.png
  CHESS GAME/index.html
Labels: Hard, Synapse

#13 Tic-Tac-Toe
  Tic-Tac-Toe/Over.mp3
  Tic-Tac-Toe/README.md
  Tic-Tac-Toe/Tic_tac_toe.png
  Tic-Tac-Toe/background.mp3
  Tic-Tac-Toe/css/style.css
  Tic-Tac-Toe/dance.gif
  Tic-Tac-Toe/index.html
  Tic-Tac-Toe/js/script.js
  Tic-Tac-Toe/turn.mp3
Labels: Medium, Synapse

#14 1st commit(portfolio-3.0)
  PORTFOLIO-3.0/README.md
  PORTFOLIO-3.0/css/style.css
  PORTFOLIO-3.0/image/project1.png
  PORTFOLIO-3.0/image/project2.png
  PORTFOLIO-3.0/image/project3.png
  PORTFOLIO-3.0/image/project4.png
  PORTFOLIO-3.0/image/project5.png
  PORTFOLIO-3.0/image/project6.png
  PORTFOLIO-3.0/image/project7.png
  PORTFOLIO-3.0/image/project8.png
  PORTFOLIO-3.0/image/user.png
  PORTFOLIO-3.0/index.html
  PORTFOLIO-3.0/js/script.js
Labels: Medium, Synapse

#16 Basic Calculator
  Basic Calculator/Calculator.html
  Basic Calculator/README.md
  Basic Calculator/css/style.css
  Basic Calculator/css/utils.css
  Basic Calculator/js/script.js
Labels: Easy, Synapse

#19 23-Pennies-COMMIT
  23 Pennies game/README.md
  23 Pennies game/index.html
  23 Pennies game/script.js
  23 Pennies game/style.css
Labels: Easy, Synapse

#20 Created TO-DO-LIST
  TO-DO-LIST/Image/Soumyajit.png
  TO-DO-LIST/Image/delete.png
  TO-DO-LIST/Image/edit.png
  TO-DO-LIST/Image/screencapture-127-0-0-1-5500-TO-DO-LIST-to-do-html-2023-01-06-13_45_01.png
  TO-DO-LIST/Image/texture_background_2.jpg
  TO-DO-LIST/README.md
  TO-DO-LIST/favicon/about.txt
  TO-DO-LIST/favicon/favicon.ico
  TO-DO-LIST/favicon/site.webmanifest
  TO-DO-LIST/light-dark-mode.js
  TO-DO-LIST/to_do.css
  TO-DO-LIST/to_do.html
  TO-DO-LIST/to_do.js
Labels: Easy, Synapse

#21 Adding a simple landing page Eduhub v0.1
  EDUHUB-online_learning_platform/.vscode/settings.json
  EDUHUB-online_learning_platform/README.md
  EDUHUB-online_learning_platform/images/5059e279473940f1a96965353c8efc41.png
  EDUHUB-online_learning_platform/images/LOGO.jpg
  EDUHUB-online_learning_platform/images/Niladri.png
  EDUHUB-online_learning_platform/images/algorithm.png
  EDUHUB-online_learning_platform/images/arnab.jpg
  EDUHUB-online_learning_platform/images/banner image.svg
  EDUHUB-online_learning_platform/images/bookstack.svg
  EDUHUB-online_learning_platform/images/certificate.svg
  EDUHUB-online_learning_platform/images/conversation.svg
  EDUHUB-online_learning_platform/images/dance.svg
  EDUHUB-online_learning_platform/images/data.png
  EDUHUB-online_learning_platform/images/download.svg
  EDUHUB-online_learning_platform/images/educator.svg
  EDUHUB-online_learning_platform/images/graduate.svg
  EDUHUB-online_learning_platform/images/graphic-design.png
  EDUHUB-online_learning_platform/images/happy-cute-kid-boy-study-using-new-laptop-167742855.jpg
  EDUHUB-online_learning_platform/images/sunny.jpg
  EDUHUB-online_learning_platform/images/tree.svg
  EDUHUB-online_learning_platform/images/tuhin.jpg
  EDUHUB-online_learning_platform/images/undraw_engineering_team_a7n2.svg
  EDUHUB-online_learning_platform/index.html
  EDUHUB-online_learning_platform/package-lock.json
  EDUHUB-online_learning_platform/package.json
  EDUHUB-online_learning_platform/style.css
  EDUHUB-online_learning_platform/tailwind.config.js
Labels: Hard, Synapse

#15 QUIZ
  QUIZ/Image1.jpg
  QUIZ/Readme.md
  QUIZ/images.png
  QUIZ/index.html
  QUIZ/script.js
  QUIZ/style.css
Labels: Easy, Synapse

#22 Glassmorphism Web Design
  CREDIT CARD DESIGN WEBSITE/README.md
  CREDIT CARD DESIGN WEBSITE/chip.png
  CREDIT CARD DESIGN WEBSITE/index.html
  CREDIT CARD DESIGN WEBSITE/mastercard.jpg
  CREDIT CARD DESIGN WEBSITE/reset.css
  CREDIT CARD DESIGN WEBSITE/style.css
  Glassmorphism Web Design/README.md
  Glassmorphism Web Design/back.png
  Glassmorphism Web Design/facebook.png
  Glassmorphism Web Design/index.html
  Glassmorphism Web Design/profile.jpg
  Glassmorphism Web Design/style.css
  Glassmorphism Web Design/telegram.png
  Glassmorphism Web Design/twitter.png
  Glassmorphism Web Design/vanilla-tilt.js
Labels: Medium, Synapse

#25 Word Scramble Game Using html,css, and JavaScript.
  Word Scramble Game/Readme.md
  Word Scramble Game/bg.mp3
  Word Scramble Game/correct.mp3
  Word Scramble Game/index.html
  Word Scramble Game/list.js
  Word Scramble Game/over.mp3
  Word Scramble Game/script.js
  Word Scramble Game/style.css
  Word Scramble Game/wrong.mp3
Labels: Medium, Synapse

#26 Add Movie Rating App
  Movie-Rating-App/README.md
  Movie-Rating-App/index.html
  Movie-Rating-App/key.js
  Movie-Rating-App/script.js
  Movie-Rating-App/star.png
  Movie-Rating-App/style.css
Labels: Medium, Synapse

#23 The Simon Game
  Simon Game Challenge Completed/Readme.md
  Simon Game Challenge Completed/game.js
  Simon Game Challenge Completed/index.html
  Simon Game Challenge Completed/sounds/blue.mp3
  Simon Game Challenge Completed/sounds/green.mp3
  Simon Game Challenge Completed/sounds/red.mp3
  Simon Game Challenge Completed/sounds/wrong.mp3
  Simon Game Challenge Completed/sounds/yellow.mp3
  Simon Game Challenge Completed/styles.css
Labels: Medium, Synapse

#17 Piano using js added
  Piano/index.html
  Piano/index.js
  Piano/keys/key01.mp3
  Piano/keys/key02.mp3
  Piano/keys/key03.mp3
  Piano/keys/key04.mp3
  Piano/keys/key05.mp3
  Piano/keys/key06.mp3
  Piano/keys/key07.mp3
  Piano/keys/key08.mp3
  Piano/keys/key09.mp3
  Piano/keys/key10.mp3
  Piano/keys/key11.mp3
  Piano/keys/key12.mp3
  Piano/keys/key13.mp3
  Piano/keys/key14.mp3
  Piano/keys/key15.mp3
  Piano/keys/key16.mp3
  Piano/keys/key17.mp3
  Piano/keys/key18.mp3
  Piano/keys/key19.mp3
  Piano/keys/key20.mp3
  Piano/keys/key21.mp3
  Piano/keys/key22.mp3
  Piano/keys/key23.mp3
  Piano/keys/key24.mp3
  Piano/readme.md
  Piano/screenshot/demo_piano.mp4
  Piano/screenshot/photo_2023-01-05_22-39-29.jpg
  Piano/screenshot/piano.png
  Piano/styles.css
Labels: Medium, Synapse

#27 Price Plan - @EmberTSeal
  Price-Plan/README.md
  Price-Plan/animation.css
  Price-Plan/design/590.avif
  Price-Plan/design/final_mobile.png
  Price-Plan/design/final_tablet.png
  Price-Plan/design/final_wide.png
  Price-Plan/design/hover.png
  Price-Plan/design/ticket.png
  Price-Plan/index.html
  Price-Plan/style.css
Labels: Medium, Synapse

#31 Hover Board Project
  Hoverboard/README.md
  Hoverboard/index.html
  Hoverboard/script.js
  Hoverboard/style.css
Labels: Easy, Synapse

#30 1ST-commit-(food-o-website)
  FOOD WEBSITE-SD/README.md
  FOOD WEBSITE-SD/css/style.css
  FOOD WEBSITE-SD/images/about-img.png
  FOOD WEBSITE-SD/images/dish-1.png
  FOOD WEBSITE-SD/images/dish-2.png
  FOOD WEBSITE-SD/images/dish-3.png
  FOOD WEBSITE-SD/images/dish-4.png
  FOOD WEBSITE-SD/images/dish-5.png
  FOOD WEBSITE-SD/images/dish-6.png
  FOOD WEBSITE-SD/images/home-img-1.png
  FOOD WEBSITE-SD/images/home-img-2.png
  FOOD WEBSITE-SD/images/home-img-3.png
  FOOD WEBSITE-SD/images/loader.gif
  FOOD WEBSITE-SD/images/menu-1.jpg
  FOOD WEBSITE-SD/images/menu-2.jpg
  FOOD WEBSITE-SD/images/menu-3.jpg
  FOOD WEBSITE-SD/images/menu-4.jpg
  FOOD WEBSITE-SD/images/menu-5.jpg
  FOOD WEBSITE-SD/images/menu-6.jpg
  FOOD WEBSITE-SD/images/menu-7.jpg
  FOOD WEBSITE-SD/images/menu-8.jpg
  FOOD WEBSITE-SD/images/menu-9.jpg
  FOOD WEBSITE-SD/images/pic-1.png
  FOOD WEBSITE-SD/images/pic-2.png
  FOOD WEBSITE-SD/images/pic-3.png
  FOOD WEBSITE-SD/images/pic-4.png
  FOOD WEBSITE-SD/index.html
  FOOD WEBSITE-SD/js/script.js
Labels: Medium, Synapse

#28 Analog Clock
  Analog Clock/README.md
  Analog Clock/clock.html
  Analog Clock/clock.png
  Analog Clock/script.js
  Analog Clock/style.css
Labels: Easy, Synapse

#33 Weather App
  Login Form/README.md
  Login Form/avatar.png
  Login Form/bg.png
  Login Form/index.html
  Login Form/main.js
  Login Form/style.css
  Login Form/wave.jpg
  Weather App/LICENSE
  Weather App/README.md
  Weather App/package-lock.json
  Weather App/package.json
  Weather App/public/favicon.ico
  Weather App/public/index.html
  Weather App/public/logo192.png
  Weather App/public/logo512.png
  Weather App/public/manifest.json
  Weather App/public/robots.txt
  Weather App/src/App.css
  Weather App/src/App.js
  Weather App/src/App.test.js
  Weather App/src/components/Tempapp.js
  Weather App/src/components/css/blue2.jpg
  Weather App/src/components/css/style.css
  Weather App/src/index.css
  Weather App/src/index.js
  Weather App/src/logo.svg
  Weather App/src/reportWebVitals.js
  Weather App/src/setupTests.js
Labels: Hard, Synapse

#35 Password generator
  Password Generator/README.md
  Password Generator/index.html
  Password Generator/script.js
  Password Generator/style.css
Labels: Easy, Synapse

#36 Random Card Generator
  Random Card Generator/Readme.md
  Random Card Generator/index.html
  Random Card Generator/script.js
  Random Card Generator/style.css
Labels: Medium, Synapse

#34 QR CODE GENERATOR
  QR CODE GENERATOR/Readme.md
  QR CODE GENERATOR/index.html
  QR CODE GENERATOR/qr.png
  QR CODE GENERATOR/script.js
  QR CODE GENERATOR/style.css
Labels: good first issue, Hard, Synapse

#37 Evm dummy
  Calander design/Readme.md
  EVM DUMMY/CONG.png
  EVM DUMMY/CPI.png
  EVM DUMMY/Readme.md
  EVM DUMMY/download (1).png
  EVM DUMMY/download.jpg
  EVM DUMMY/download.png
  EVM DUMMY/images.jpg
  EVM DUMMY/index.html
  EVM DUMMY/pixel_wbdy4n.png
  EVM DUMMY/script.js
  EVM DUMMY/style.css
  EVM DUMMY/undraw_voting_nvu7.png
Labels: Easy, Synapse

#39 1st-commit-COFFEE-SHOP
  COFFEE-WEBSITE/README.md
  COFFEE-WEBSITE/css/style.css
  COFFEE-WEBSITE/images/about-img.jpeg
  COFFEE-WEBSITE/images/blog-1.jpeg
  COFFEE-WEBSITE/images/blog-2.jpeg
  COFFEE-WEBSITE/images/blog-3.jpeg
  COFFEE-WEBSITE/images/cart-item-1.png
  COFFEE-WEBSITE/images/cart-item-2.png
  COFFEE-WEBSITE/images/cart-item-3.png
  COFFEE-WEBSITE/images/cart-item-4.png
  COFFEE-WEBSITE/images/home-img.jpeg
  COFFEE-WEBSITE/images/logo.png
  COFFEE-WEBSITE/images/menu-1.png
  COFFEE-WEBSITE/images/menu-2.png
  COFFEE-WEBSITE/images/menu-3.png
  COFFEE-WEBSITE/images/menu-4.png
  COFFEE-WEBSITE/images/menu-5.png
  COFFEE-WEBSITE/images/menu-6.png
  COFFEE-WEBSITE/images/pic-1.png
  COFFEE-WEBSITE/images/pic-2.png
  COFFEE-WEBSITE/images/pic-3.png
  COFFEE-WEBSITE/images/product-1.png
  COFFEE-WEBSITE/images/product-2.png
  COFFEE-WEBSITE/images/product-3.png
  COFFEE-WEBSITE/images/quote-img.png
  COFFEE-WEBSITE/index.html
  COFFEE-WEBSITE/js/script.js
Labels: Easy, Synapse

#40 Jokes Generator App
  Jokes Generator/README.md
  Jokes Generator/logo.png
  Jokes Generator/manifest.json
  Jokes Generator/popup.html
  Jokes Generator/script.js
  Jokes Generator/style.css
Labels: Easy, Synapse

#45 Animated Countdown
  Animated countdown/README.md
  Animated countdown/index.html
  Animated countdown/script.js
  Animated countdown/style.css
Labels: Easy, Synapse

#47 Text To Speech Converter
  Text To Speech Converter/Readme.md
  Text To Speech Converter/index.html
  Text To Speech Converter/script.js
  Text To Speech Converter/style.css
Labels: Medium, Synapse

#48 1st-commit(grocery-shop)
  Grocery-shop-Website/README.md
  Grocery-shop-Website/images/banner-1.jpg
  Grocery-shop-Website/images/banner-2.jpg
  Grocery-shop-Website/images/category-1.png
  Grocery-shop-Website/images/category-2.png
  Grocery-shop-Website/images/category-3.png
  Grocery-shop-Website/images/category-4.png
  Grocery-shop-Website/images/deal-bg.jpg
  Grocery-shop-Website/images/deal-img2.png
  Grocery-shop-Website/images/home-img.png
  Grocery-shop-Website/images/newsletter-bg.jpg
  Grocery-shop-Website/images/product-1.png
  Grocery-shop-Website/images/product-2.png
  Grocery-shop-Website/images/product-3.png
  Grocery-shop-Website/images/product-4.png
  Grocery-shop-Website/images/product-5.png
  Grocery-shop-Website/images/product-6.png
  Grocery-shop-Website/images/product-7.png
  Grocery-shop-Website/images/product-8.png
  Grocery-shop-Website/images/product-9.png
  Grocery-shop-Website/index.html
  Grocery-shop-Website/script.js
  Grocery-shop-Website/style.css
Labels: Medium, Synapse

#50 Movie App
  movie App/README.md
  movie App/index.html
  movie App/script.js
  movie App/style.css
Labels: Medium, Synapse

#49 Yummy
  Yummy/Readme.md
  Yummy/biriyani-bg.jpg
  Yummy/favicon.jpeg
  Yummy/index.html
  Yummy/script.js
  Yummy/style.css
Labels: Medium, Synapse

#51 Notes App
  notes app/README.md
  notes app/index.html
  notes app/script.js
  notes app/style.css
Labels: Easy, Synapse

#53 Drawing App
  Drawing App/README.md
  Drawing App/index.html
  Drawing App/script.js
  Drawing App/style.css
Labels: Medium, Synapse

#52 Scientific calculator
  SCIENTIFIC CALCULATOR/README.md
  SCIENTIFIC CALCULATOR/index.html
  SCIENTIFIC CALCULATOR/script.js
  SCIENTIFIC CALCULATOR/style.css
  SCIENTIFIC CALCULATOR/util.css
Labels: Medium, Synapse

#54 Quiz App
  Quiz app/README.md
  Quiz app/index.html
  Quiz app/script.js
  Quiz app/style.css
Labels: Easy, Synapse

#57 Update ReadMe.md
  hospitrack/.gitignore
  hospitrack/README.md
  hospitrack/package-lock.json
  hospitrack/package.json
  hospitrack/public/favicon.ico
  hospitrack/public/index.html
  hospitrack/public/logo192.png
  hospitrack/public/logo512.png
  hospitrack/public/manifest.json
  hospitrack/public/robots.txt
  hospitrack/src/App.css
  hospitrack/src/App.js
  hospitrack/src/App.test.js
  hospitrack/src/Home.css
  hospitrack/src/Home.jsx
  hospitrack/src/index.css
  hospitrack/src/index.js
  hospitrack/src/reportWebVitals.js
  hospitrack/src/setupTests.js
  hospitrack/tailwind.config.js
Labels: Medium, Synapse

#58 1st-commit(travel website)
  Travel Website-SD/README.md
  Travel Website-SD/css/style.css
  Travel Website-SD/images/about-img.jpg
  Travel Website-SD/images/category-1.jpg
  Travel Website-SD/images/category-2.jpg
  Travel Website-SD/images/category-3.jpg
  Travel Website-SD/images/category-4.jpg
  Travel Website-SD/images/client-logo-1.png
  Travel Website-SD/images/client-logo-2.png
  Travel Website-SD/images/client-logo-3.png
  Travel Website-SD/images/client-logo-4.png
  Travel Website-SD/images/footer-bg.jpg
  Travel Website-SD/images/home-bg-1.jpg
  Travel Website-SD/images/home-bg-2.jpg
  Travel Website-SD/images/home-bg-3.jpg
  Travel Website-SD/images/img-1.jpg
  Travel Website-SD/images/img-2.jpg
  Travel Website-SD/images/img-3.jpg
  Travel Website-SD/images/img-4.jpg
  Travel Website-SD/images/img-5.jpg
  Travel Website-SD/images/img-6.jpg
  Travel Website-SD/images/pic-1.png
  Travel Website-SD/images/pic-2.png
  Travel Website-SD/images/pic-3.png
  Travel Website-SD/images/pic-4.png
  Travel Website-SD/images/pic-5.png
  Travel Website-SD/images/pic-6.png
  Travel Website-SD/images/product-1.jpg
  Travel Website-SD/images/product-2.jpg
  Travel Website-SD/images/product-3.JPG
  Travel Website-SD/images/product-4.JPG
  Travel Website-SD/images/product-5.jpg
  Travel Website-SD/images/product-6.jpg
  Travel Website-SD/images/serv-1.png
  Travel Website-SD/images/serv-2.png
  Travel Website-SD/images/serv-3.png
  Travel Website-SD/images/serv-4.png
  Travel Website-SD/images/serv-5.png
  Travel Website-SD/images/serv-6.png
  Travel Website-SD/index.html
  Travel Website-SD/js/script.js
Labels: Medium, Synapse

#59 Resize and Compress Images
  Resize and Compress Images/Readme.md
  Resize and Compress Images/index.html
  Resize and Compress Images/script.js
  Resize and Compress Images/style.css
  Resize and Compress Images/upload-icon.jpg
Labels: Medium, Synapse

#61 Sorting Visualiser using React
  Sorting Visualiser using React/.gitignore
  Sorting Visualiser using React/App.css
  Sorting Visualiser using React/App.js
  Sorting Visualiser using React/App.test.js
  Sorting Visualiser using React/README.md
  Sorting Visualiser using React/Readme.md
  Sorting Visualiser using React/SortingAlgorithms.js
  Sorting Visualiser using React/SortingVisualiser.css
  Sorting Visualiser using React/favicon.ico
  Sorting Visualiser using React/index.css
  Sorting Visualiser using React/index.html
  Sorting Visualiser using React/index.js
  Sorting Visualiser using React/logo.svg
  Sorting Visualiser using React/logo192.png
  Sorting Visualiser using React/logo512.png
  Sorting Visualiser using React/manifest.json
  Sorting Visualiser using React/package-lock.json
  Sorting Visualiser using React/package.json
  Sorting Visualiser using React/reportWebVitals.js
  Sorting Visualiser using React/robots.txt
  Sorting Visualiser using React/setupTests.js
  Sorting Visualiser using React/sortingVisualiser.jsx
  Sorting Visualiser using React/tempCodeRunnerFile.js
Labels: Medium, Synapse

#62 Image Editor App
  Image Editor App/Choose_image.svg
  Image Editor App/README.md
  Image Editor App/Responsive.css
  Image Editor App/index.html
  Image Editor App/script.js
  Image Editor App/style.css
Labels: Medium, Synapse

#64 Flipkart_Cloning
  FLIPKART_CLONING/README.md
  FLIPKART_CLONING/flipkart.css
  FLIPKART_CLONING/flipkart3.css
  FLIPKART_CLONING/index.html
  FLIPKART_CLONING/logo.png
  FLIPKART_CLONING/style.css
Labels: Medium, Synapse

#65 Memory Card Game
  Memory Card Game/Readme.md
  Memory Card Game/images/img-1.png
  Memory Card Game/images/img-2.png
  Memory Card Game/images/img-3.png
  Memory Card Game/images/img-4.png
  Memory Card Game/images/img-5.png
  Memory Card Game/images/img-6.png
  Memory Card Game/images/img-7.png
  Memory Card Game/images/img-8.png
  Memory Card Game/images/que_icon.svg
  Memory Card Game/index.html
  Memory Card Game/script.js
  Memory Card Game/style.css
Labels: Easy, Synapse

#66 Memory Game
  Memory game/README.md
  Memory game/css/img/1.png
  Memory game/css/img/10.png
  Memory game/css/img/11.png
  Memory game/css/img/12.png
  Memory game/css/img/2.png
  Memory game/css/img/3.png
  Memory game/css/img/4.png
  Memory game/css/img/5.png
  Memory game/css/img/6.png
  Memory game/css/img/7.png
  Memory game/css/img/8.png
  Memory game/css/img/9.png
  Memory game/css/style.css
  Memory game/index.html
  Memory game/script.js
Labels: Medium, Synapse

#67 Budget Tracker
  Budget Tracker/Readme.md
  Budget Tracker/index.html
  Budget Tracker/script.js
  Budget Tracker/style.css
Labels: Medium, Synapse

#68 1ST-COMMIT(MENJA GAME)
  MENJA-GAME/README.md
  MENJA-GAME/app.js
  MENJA-GAME/image/Menja-game.png
  MENJA-GAME/index.html
  MENJA-GAME/style.css
Labels: Medium, Synapse

#70 English Dictionary
  English Dictionary/Readme.md
  English Dictionary/index.html
  English Dictionary/script.js
  English Dictionary/style.css
Labels: Medium, Synapse

#73 ElearningWebsite
  ElearningWebsite/IoT-devices.webp
  ElearningWebsite/README.md
  ElearningWebsite/about.html
  ElearningWebsite/about1.jfif
  ElearningWebsite/c++.png
  ElearningWebsite/c.png
  ElearningWebsite/contactus.html
  ElearningWebsite/html1.png
  ElearningWebsite/index.html
  ElearningWebsite/java.webp
  ElearningWebsite/me.jpg
  ElearningWebsite/photo-1454997423871-b5215756e54d.jfif
  ElearningWebsite/photo-1584907797180-09bced365d42.jfif
  ElearningWebsite/photo-1615473274862-f814bd5143df.jfif
  ElearningWebsite/python.png
  ElearningWebsite/rocky.jpg
  ElearningWebsite/souvik.jpg
Labels: Easy, Synapse

#60 A simple debit card
  debit card project/README.md
  debit card project/chip.png
  debit card project/index.html
  debit card project/map.png
  debit card project/pattern.png
  debit card project/style.css
  debit card project/visa.png
Labels: Easy, Synapse

#75 Tetris Game
  Music Player/README.md
  Sorting Visualiser using React/README.md
  Tetris game/README.md
  Tetris game/down.png
  Tetris game/index.html
  Tetris game/leftt.png
  Tetris game/main.js
  Tetris game/pause.png
  Tetris game/play.png
  Tetris game/redo.png
  Tetris game/right.png
  Tetris game/style.css
Labels: Medium, Synapse

#76 1st-commit-(resume website)
  RESUME WEBSITE/Profile.pdf
  RESUME WEBSITE/README.md
  RESUME WEBSITE/images/soham11.jpg
  RESUME WEBSITE/images/soham12.png
  RESUME WEBSITE/images/soham13.jpg
  RESUME WEBSITE/index.html
  RESUME WEBSITE/style.css
Labels: Easy, Synapse

#81 ColorPicker
  ColorPicker/Readme.md
  ColorPicker/index.html
  ColorPicker/script.js
  ColorPicker/style.css
Labels: Easy, Synapse

#77 Word Guessing Game
  Word Guessing Game/Readme.md
  Word Guessing Game/index.html
  Word Guessing Game/js/script.js
  Word Guessing Game/js/words.js
  Word Guessing Game/style.css
Labels: Medium, Synapse

#80 1st commit(save nature website)
  Nature-Website-Design/README.md
  Nature-Website-Design/images/donate-bg.jpg
  Nature-Website-Design/images/event1.jpg
  Nature-Website-Design/images/event2.jpg
  Nature-Website-Design/images/event3.jpg
  Nature-Website-Design/images/event4.jpg
  Nature-Website-Design/images/event5.jpg
  Nature-Website-Design/images/event6.jpg
  Nature-Website-Design/images/footer-bg.jpg
  Nature-Website-Design/images/home-bg.jpg
  Nature-Website-Design/images/icon1.png
  Nature-Website-Design/images/icon2.png
  Nature-Website-Design/images/icon3.png
  Nature-Website-Design/images/icon4.png
  Nature-Website-Design/images/pic1.png
  Nature-Website-Design/images/pic2.png
  Nature-Website-Design/images/pic3.png
  Nature-Website-Design/images/pic4.png
  Nature-Website-Design/images/project-1.jpg
  Nature-Website-Design/images/project-2.jpg
  Nature-Website-Design/images/project-3.jpg
  Nature-Website-Design/images/project-4.jpg
  Nature-Website-Design/images/team1.jpg
  Nature-Website-Design/images/team2.jpg
  Nature-Website-Design/images/team3.jpg
  Nature-Website-Design/images/team4.jpg
  Nature-Website-Design/images/team5.jpg
  Nature-Website-Design/images/team6.jpg
  Nature-Website-Design/images/team7.jpg
  Nature-Website-Design/images/team8.jpg
  Nature-Website-Design/index.html
  Nature-Website-Design/script.js
  Nature-Website-Design/style.css
Labels: Medium, Synapse

#82 Paint Website
  Paint Website/Readme.md
  Paint Website/icons/brush.svg
  Paint Website/icons/circle.svg
  Paint Website/icons/eraser.svg
  Paint Website/icons/rectangle.svg
  Paint Website/icons/triangle.svg
  Paint Website/index.html
  Paint Website/script.js
  Paint Website/style.css
Labels: Medium, Synapse

#83 Videocall App UI
  Videocall App UI/README.md
  Videocall App UI/icons/icons.css
  Videocall App UI/icons/icons.html
  Videocall App UI/index.html
  Videocall App UI/script.js
  Videocall App UI/style.css
Labels: Medium, Synapse

#85 Google Clone
  Google Clone/README.md
  Google Clone/images/favicon.jpg
  Google Clone/images/logo.jpg
  Google Clone/index.html
  Google Clone/main.js
  Google Clone/style.css
Labels: Medium, Synapse

#87 1st commit-(Good app website)
  Good App Website/README.md
  Good App Website/images/about-bg.png
  Good App Website/images/about-img.png
  Good App Website/images/contact-img.png
  Good App Website/images/f-icon1.png
  Good App Website/images/f-icon2.png
  Good App Website/images/f-icon3.png
  Good App Website/images/footer-bg.png
  Good App Website/images/home-bg-img.png
  Good App Website/images/home-img.png
  Good App Website/images/pic1.png
  Good App Website/images/pic2.png
  Good App Website/images/pic3.png
  Good App Website/images/subscribe-bg.png
  Good App Website/index.html
  Good App Website/style.css
Labels: Medium, Synapse

#88 CLOCK
  CLOCK/README.md
  CLOCK/index.html
  CLOCK/script.js
  CLOCK/style.css
Labels: Easy, Synapse

#89 Movie Summary App
  Movie search app/Readme.md
  Movie search app/index.html
  Movie search app/script.js
  Movie search app/style.css
Labels: Easy, Synapse

#92 Dash Car Racing Game
  Dash Car racing Game/1icon.png
  Dash Car racing Game/README.md
  Dash Car racing Game/icon.png
  Dash Car racing Game/images/car04.png
  Dash Car racing Game/images/cloud.jpg
  Dash Car racing Game/images/finish.png
  Dash Car racing Game/images/hero.png
  Dash Car racing Game/images/tree.png
  Dash Car racing Game/index.html
  Dash Car racing Game/javascript/1.js
  Dash Car racing Game/javascript/null.js
Labels: Medium, Synapse

#95 clothing website commit
  Clothing website DB/clothing/404.css
  Clothing website DB/clothing/404.html
  Clothing website DB/clothing/404.png
  Clothing website DB/clothing/README.md
  Clothing website DB/clothing/accessories-collection.png
  Clothing website DB/clothing/arrow.png
  Clothing website DB/clothing/card1.png
  Clothing website DB/clothing/card10.png
  Clothing website DB/clothing/card11.png
  Clothing website DB/clothing/card12.png
  Clothing website DB/clothing/card2.png
  Clothing website DB/clothing/card3.png
  Clothing website DB/clothing/card4.png
  Clothing website DB/clothing/card5.png
  Clothing website DB/clothing/card6.png
  Clothing website DB/clothing/card7.png
  Clothing website DB/clothing/card8.png
  Clothing website DB/clothing/card9.png
  Clothing website DB/clothing/cart.png
  Clothing website DB/clothing/dark-logo.png
  Clothing website DB/clothing/footer.css
  Clothing website DB/clothing/footer.js
  Clothing website DB/clothing/header.png
  Clothing website DB/clothing/home.js
  Clothing website DB/clothing/index.html
  Clothing website DB/clothing/light-logo.png
  Clothing website DB/clothing/men-collection.png
  Clothing website DB/clothing/nav.js
  Clothing website DB/clothing/product image 1.png
  Clothing website DB/clothing/product image 2.png
  Clothing website DB/clothing/product image 3.png
  Clothing website DB/clothing/product image 4.png
  Clothing website DB/clothing/product.css
  Clothing website DB/clothing/product.html
  Clothing website DB/clothing/product.js
  Clothing website DB/clothing/search.css
  Clothing website DB/clothing/search.html
  Clothing website DB/clothing/shirt1.webp
  Clothing website DB/clothing/shirt2.webp
  Clothing website DB/clothing/shirt3.webp
  Clothing website DB/clothing/shirt4.jpg
  Clothing website DB/clothing/shoe1.jpg
  Clothing website DB/clothing/shoe2.webp
  Clothing website DB/clothing/shoe3.webp
  Clothing website DB/clothing/shoe4.webp
  Clothing website DB/clothing/style.css
  Clothing website DB/clothing/user.png
  Clothing website DB/clothing/women-collection.png
Labels: Medium, Synapse

#96 1st-commit(business website)
  Business Website/README.md
  Business Website/css/style.css
  Business Website/images/about-img.png
  Business Website/images/cloud.png
  Business Website/images/p-1.png
  Business Website/images/p-2.png
  Business Website/images/p-3.png
  Business Website/images/pic-1.png
  Business Website/images/pic-2.png
  Business Website/images/pic-3.png
  Business Website/images/port-img1.jpg
  Business Website/images/port-img2.jpg
  Business Website/images/port-img3.jpg
  Business Website/images/port-img4.jpg
  Business Website/images/port-img5.jpg
  Business Website/images/port-img6.jpg
  Business Website/images/rocket.svg
  Business Website/images/s-1.png
  Business Website/images/s-2.png
  Business Website/images/s-3.png
  Business Website/images/s-4.png
  Business Website/images/s-5.png
  Business Website/images/s-6.png
  Business Website/index.html
  Business Website/js/script.js
Labels: Medium, Synapse

#94 password Strength background
  password Strength background/README.md
  password Strength background/index.html
  password Strength background/script.js
  password Strength background/style.css
Labels: Easy, Synapse

#102 Product_Landing_Page
  PRODUCT LANDING PAGE/README.md
  PRODUCT LANDING PAGE/index.html
  PRODUCT LANDING PAGE/style.css
  TEMPERATURE CONVERTER/README.md
  TEMPERATURE CONVERTER/index.html
  TEMPERATURE CONVERTER/script.js
  TEMPERATURE CONVERTER/style.css
Labels: Hard, Synapse

#97 1st-commit-(car booking or buy or sell website)
  car-Booking-Website/README.md
  car-Booking-Website/css/style.css
  car-Booking-Website/image/car-1.png
  car-Booking-Website/image/car-2.png
  car-Booking-Website/image/car-3.png
  car-Booking-Website/image/car-4.png
  car-Booking-Website/image/car-5.png
  car-Booking-Website/image/car-6.png
  car-Booking-Website/image/car-7.png
  car-Booking-Website/image/car-8.png
  car-Booking-Website/image/home-img.png
  car-Booking-Website/image/letter-bg.png
  car-Booking-Website/image/pic-1.png
  car-Booking-Website/image/pic-2.png
  car-Booking-Website/image/pic-3.png
  car-Booking-Website/image/pic-4.png
  car-Booking-Website/image/pic-5.png
  car-Booking-Website/image/pic-6.png
  car-Booking-Website/image/vehicle-1.png
  car-Booking-Website/image/vehicle-2.png
  car-Booking-Website/image/vehicle-3.png
  car-Booking-Website/image/vehicle-4.png
  car-Booking-Website/image/vehicle-5.png
  car-Booking-Website/image/vehicle-6.png
  car-Booking-Website/index.html
  car-Booking-Website/js/script.js
Labels: Medium, Synapse

#93 QR Code Reader or Scanner
  QR Code Reader or Scanner/Readme.md
  QR Code Reader or Scanner/index.html
  QR Code Reader or Scanner/script.js
  QR Code Reader or Scanner/style.css
Labels: Medium, Synapse

#100 Live Code editor
  live code editor/README.md
  live code editor/images/CSS.png
  live code editor/images/html.png
  live code editor/images/js.png
  live code editor/index.html
  live code editor/script.js
  live code editor/style.css
Labels: Medium, Synapse

#103 1st commit (pet food shop)
  Pet-Food_Shop_Website/README.md
  Pet-Food_Shop_Website/images/c1.webp
  Pet-Food_Shop_Website/images/c2.webp
  Pet-Food_Shop_Website/images/c3.webp
  Pet-Food_Shop_Website/images/c4.webp
  Pet-Food_Shop_Website/images/contact-bg.webp
  Pet-Food_Shop_Website/images/deal-bg.webp
  Pet-Food_Shop_Website/images/home-bg.webp
  Pet-Food_Shop_Website/images/offer-img1.webp
  Pet-Food_Shop_Website/images/offer-img2.webp
  Pet-Food_Shop_Website/images/p1.webp
  Pet-Food_Shop_Website/images/p2.webp
  Pet-Food_Shop_Website/images/p3.webp
  Pet-Food_Shop_Website/images/p4.webp
  Pet-Food_Shop_Website/images/p5.webp
  Pet-Food_Shop_Website/images/p6.webp
  Pet-Food_Shop_Website/index.html
  Pet-Food_Shop_Website/script.js
  Pet-Food_Shop_Website/style.css
Labels: Medium, Synapse

#104 Blog_Application
  BLOG APPLICATION/README.md
  BLOG APPLICATION/index.html
  BLOG APPLICATION/script.js
  BLOG APPLICATION/style.css
Labels: Medium, Synapse

#105 Github User Details
  Github User Details/Readme.md
  Github User Details/index.html
  Github User Details/script.js
  Github User Details/style.css
Labels: Easy, Synapse

#108 Responsive Admin Website
  Responsive Admin Dashboard/README.md
  Responsive Admin Dashboard/assets/css/style.css
  Responsive Admin Dashboard/assets/imgs/customer01.jpg
  Responsive Admin Dashboard/assets/imgs/customer02.jpg
  Responsive Admin Dashboard/assets/js/main.js
  Responsive Admin Dashboard/index.html
Labels: Hard, Synapse

#106 BMI Calculator
  BMI Calculator/README.md
  BMI Calculator/bmi.js
  BMI Calculator/index.html
  BMI Calculator/style.css
Labels: Medium, Synapse

#112 Online Magazine Website
  Online Magazine Website/README.md
  Online Magazine Website/article.html
  Online Magazine Website/css/main.css
  Online Magazine Website/images/1.png
  Online Magazine Website/images/comment.png
  Online Magazine Website/images/facebook.png
  Online Magazine Website/images/instagram.png
  Online Magazine Website/images/logo.png
  Online Magazine Website/images/menu.png
  Online Magazine Website/images/search.png
  Online Magazine Website/images/twitter.png
  Online Magazine Website/index.html
  Online Magazine Website/js/jquery.min.js
  Online Magazine Website/js/jquery.placeholder.js
  Online Magazine Website/js/main.js
Labels: Medium, Synapse

#111 Lobe Tour Clone
  Lobe-Tour-Clone/README.md
  Lobe-Tour-Clone/final/small_Lobe-Tour.png
  Lobe-Tour-Clone/final/ticket.png
  Lobe-Tour-Clone/final/wide_Lobe-Tour.png
  Lobe-Tour-Clone/icons/reddit-round.svg
  Lobe-Tour-Clone/icons/robot-solid.svg
  Lobe-Tour-Clone/icons/twitter-round-icon.svg
  Lobe-Tour-Clone/icons/youtube-round.svg
  Lobe-Tour-Clone/index.html
  Lobe-Tour-Clone/index.js
  Lobe-Tour-Clone/style.css
Labels: Medium, Synapse

#121 1st-commit(christmas website)
  Christmas-Gift-Website/README.md
  Christmas-Gift-Website/css/style.css
  Christmas-Gift-Website/images/about-img.png
  Christmas-Gift-Website/images/bg-img.png
  Christmas-Gift-Website/images/footer-img.webp
  Christmas-Gift-Website/images/g-img-1.webp
  Christmas-Gift-Website/images/g-img-2.webp
  Christmas-Gift-Website/images/g-img-3.webp
  Christmas-Gift-Website/images/g-img-4.webp
  Christmas-Gift-Website/images/g-img-5.webp
  Christmas-Gift-Website/images/g-img-6.webp
  Christmas-Gift-Website/images/home-bg.png
  Christmas-Gift-Website/images/icon-01.png
  Christmas-Gift-Website/images/icon-02.png
  Christmas-Gift-Website/images/icon-03.png
  Christmas-Gift-Website/images/icon-04.png
  Christmas-Gift-Website/images/icon-05.png
  Christmas-Gift-Website/images/icon-06.png
  Christmas-Gift-Website/images/menu-btn-bg.webp
  Christmas-Gift-Website/images/pic-1.png
  Christmas-Gift-Website/images/pic-2.png
  Christmas-Gift-Website/images/pic-3.png
  Christmas-Gift-Website/images/pic-4.png
  Christmas-Gift-Website/images/pic-5.png
  Christmas-Gift-Website/images/pricing-table-bg-1.png
  Christmas-Gift-Website/images/pricing-table-bg-2.png
  Christmas-Gift-Website/images/pricing-table-bg-3.png
  Christmas-Gift-Website/index.html
  Christmas-Gift-Website/js/script.js
Labels: Medium, Synapse

#120 Puzzle Game
  Puzzle Game/Readme.md
  Puzzle Game/index.html
  Puzzle Game/script.js
  Puzzle Game/style.css
Labels: Easy, Synapse

#118 Spotify Clone
  SpotifyClone/README.md
  SpotifyClone/css/style.css
  SpotifyClone/images/capa.png
  SpotifyClone/images/facebook.png
  SpotifyClone/images/favicon.png
  SpotifyClone/images/img1.jpg
  SpotifyClone/images/img2.jpg
  SpotifyClone/images/img3.jpg
  SpotifyClone/images/img4.jpg
  SpotifyClone/images/instagram.png
  SpotifyClone/images/iphone1.png
  SpotifyClone/images/iphone2.png
  SpotifyClone/images/iphone3.png
  SpotifyClone/images/ruido.png
  SpotifyClone/images/spotify.svg
  SpotifyClone/images/twitter.png
  SpotifyClone/index.html
Labels: Easy, Synapse

#122 Starbucks_Clone
  Starbucks_Clone/Readme.md
  Starbucks_Clone/assets/images/box-b.png
  Starbucks_Clone/assets/images/box-c.png
  Starbucks_Clone/assets/images/box-d.png
  Starbucks_Clone/assets/images/box-e.jpg
  Starbucks_Clone/assets/images/box-f1.jpg
  Starbucks_Clone/assets/images/box-f2.jpg
  Starbucks_Clone/assets/images/logo.svg
  Starbucks_Clone/assets/images/marker.svg
  Starbucks_Clone/assets/images/social-facebook.svg
  Starbucks_Clone/assets/images/social-instagram.svg
  Starbucks_Clone/assets/images/social-pinterest.svg
  Starbucks_Clone/assets/images/social-spotify.svg
  Starbucks_Clone/assets/images/social-twitter.svg
  Starbucks_Clone/assets/images/social-youtube.svg
  Starbucks_Clone/index.html
  Starbucks_Clone/script.js
  Starbucks_Clone/style.css
Labels: Easy, Synapse

#123 Cryptex - Crypto trading Website
  cryptex/README.md
  cryptex/assets/css/style.css
  cryptex/assets/images/about-banner.png
  cryptex/assets/images/app-banner.png
  cryptex/assets/images/appstore.png
  cryptex/assets/images/chart-1.svg
  cryptex/assets/images/chart-2.svg
  cryptex/assets/images/coin-1.svg
  cryptex/assets/images/coin-2.svg
  cryptex/assets/images/coin-3.svg
  cryptex/assets/images/coin-4.svg
  cryptex/assets/images/coin-5.svg
  cryptex/assets/images/coin-6.svg
  cryptex/assets/images/coin-7.svg
  cryptex/assets/images/coin-8.svg
  cryptex/assets/images/connect-line.png
  cryptex/assets/images/googleplay.png
  cryptex/assets/images/hero-banner.png
  cryptex/assets/images/instruction-1.png
  cryptex/assets/images/instruction-2.png
  cryptex/assets/images/instruction-3.png
  cryptex/assets/images/instruction-4.png
  cryptex/assets/images/logo.svg
  cryptex/assets/js/script.js
  cryptex/favicon.svg
  cryptex/index.html
Labels: Medium, Synapse

#124 Word Charecter Counter
  word_charecter_counter/index.html
  word_charecter_counter/readme.md
  word_charecter_counter/script.js
  word_charecter_counter/style.css
Labels: Medium, Synapse

#125 1st commit-(plant selling website)
  Plant-Selling website/README.md
  Plant-Selling website/images/banner1.jpg
  Plant-Selling website/images/banner2.jpg
  Plant-Selling website/images/cat1.jpg
  Plant-Selling website/images/cat2.jpg
  Plant-Selling website/images/cat3.jpg
  Plant-Selling website/images/cat4.jpg
  Plant-Selling website/images/deal-img.jpg
  Plant-Selling website/images/icon1.png
  Plant-Selling website/images/icon2.png
  Plant-Selling website/images/icon3.png
  Plant-Selling website/images/icon4.png
  Plant-Selling website/images/product1.jpg
  Plant-Selling website/images/product2.jpg
  Plant-Selling website/images/product3.jpg
  Plant-Selling website/images/product4.jpg
  Plant-Selling website/images/product5.jpg
  Plant-Selling website/images/product6.jpg
  Plant-Selling website/images/slider1.jpg
  Plant-Selling website/images/slider2.jpg
  Plant-Selling website/images/slider3.jpg
  Plant-Selling website/index.html
  Plant-Selling website/script.js
  Plant-Selling website/style.css
Labels: Medium, Synapse

#127 Custom Captcha Creator
  Custom Captcha Creator/Readme.md
  Custom Captcha Creator/captcha-bg.png
  Custom Captcha Creator/index.html
  Custom Captcha Creator/script.js
  Custom Captcha Creator/style.css
Labels: Easy, Synapse

#130 Online Book Store
  Online book store/README.md
  Online book store/css/style.css
  Online book store/image/banner-bg.jpg
  Online book store/image/blog-1.jpg
  Online book store/image/blog-2.jpg
  Online book store/image/blog-3.jpg
  Online book store/image/blog-4.jpg
  Online book store/image/blog-5.jpg
  Online book store/image/book-1.png
  Online book store/image/book-10.png
  Online book store/image/book-2.png
  Online book store/image/book-3.png
  Online book store/image/book-4.png
  Online book store/image/book-5.png
  Online book store/image/book-6.png
  Online book store/image/book-7.png
  Online book store/image/book-8.png
  Online book store/image/book-9.png
  Online book store/image/book3.png
  Online book store/image/book5.png
  Online book store/image/book7.png
  Online book store/image/deal-img.jpg
  Online book store/image/letter-bg.jpg
  Online book store/image/loader-img.gif
  Online book store/image/pic-1.png
  Online book store/image/pic-2.png
  Online book store/image/pic-3.png
  Online book store/image/pic-4.png
  Online book store/image/pic-5.png
  Online book store/image/pic-6.png
  Online book store/image/stand.png
  Online book store/image/worldmap.png
  Online book store/index.html
  Online book store/js/script.js
Labels: Medium, Synapse

#131 Disney+ Hotstar Clone
  Disney+ Hotstar Clone/Readme.md
  Disney+ Hotstar Clone/images/add.png
  Disney+ Hotstar Clone/images/disney.png
  Disney+ Hotstar Clone/images/geographic.png
  Disney+ Hotstar Clone/images/logo.png
  Disney+ Hotstar Clone/images/marvel.png
  Disney+ Hotstar Clone/images/nxt.png
  Disney+ Hotstar Clone/images/pixer.png
  Disney+ Hotstar Clone/images/play.png
  Disney+ Hotstar Clone/images/poster 1.png
  Disney+ Hotstar Clone/images/poster 10.png
  Disney+ Hotstar Clone/images/poster 11.png
  Disney+ Hotstar Clone/images/poster 12.png
  Disney+ Hotstar Clone/images/poster 2.png
  Disney+ Hotstar Clone/images/poster 3.png
  Disney+ Hotstar Clone/images/poster 4.png
  Disney+ Hotstar Clone/images/poster 5.png
  Disney+ Hotstar Clone/images/poster 6.png
  Disney+ Hotstar Clone/images/poster 7.png
  Disney+ Hotstar Clone/images/poster 8.png
  Disney+ Hotstar Clone/images/poster 9.png
  Disney+ Hotstar Clone/images/pre.png
  Disney+ Hotstar Clone/images/slider 1.PNG
  Disney+ Hotstar Clone/images/slider 2.PNG
  Disney+ Hotstar Clone/images/slider 3.PNG
  Disney+ Hotstar Clone/images/slider 4.PNG
  Disney+ Hotstar Clone/images/slider 5.PNG
  Disney+ Hotstar Clone/images/star-wars.png
  Disney+ Hotstar Clone/index.html
  Disney+ Hotstar Clone/index.js
  Disney+ Hotstar Clone/styles.css
  Disney+ Hotstar Clone/videos/disney.mp4
  Disney+ Hotstar Clone/videos/geographic.mp4
  Disney+ Hotstar Clone/videos/marvel.mp4
  Disney+ Hotstar Clone/videos/pixar.mp4
  Disney+ Hotstar Clone/videos/star-war.mp4
Labels: Hard, Synapse

#132 Drewing app
  Drewing App/Readme.md
  Drewing App/index.html
  Drewing App/script.js
  Drewing App/style.css
Labels: Medium, Synapse

#133 Tom and Jerry
  Tom_And_Jerry/gameover.mp3
  Tom_And_Jerry/graphic.png
  Tom_And_Jerry/index.html
  Tom_And_Jerry/jerry.png
  Tom_And_Jerry/logo.png
  Tom_And_Jerry/music.mp3
  Tom_And_Jerry/readme.md
  Tom_And_Jerry/script.js
  Tom_And_Jerry/style.css
  Tom_And_Jerry/tom.gif
Labels: Medium, Synapse

#135 Notification Component
  Notification_Component/README.md
  Notification_Component/assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
  Notification_Component/assets/fonts/README.txt
  Notification_Component/assets/fonts/static/PlusJakartaSans-ExtraBold.ttf
  Notification_Component/assets/fonts/static/PlusJakartaSans-Medium.ttf
  Notification_Component/assets/images/avatar-angela-gray.webp
  Notification_Component/assets/images/avatar-anna-kim.webp
  Notification_Component/assets/images/avatar-jacob-thompson.webp
  Notification_Component/assets/images/avatar-kimberly-smith.webp
  Notification_Component/assets/images/avatar-mark-webber.webp
  Notification_Component/assets/images/avatar-nathan-peterson.webp
  Notification_Component/assets/images/avatar-rizky-hasanuddin.webp
  Notification_Component/assets/images/favicon-32x32.png
  Notification_Component/assets/images/image-chess.webp
  Notification_Component/final/laptop_1440px.png
  Notification_Component/final/mobile_375px.png
  Notification_Component/final/ticket.png
  Notification_Component/index.html
  Notification_Component/style.css
Labels: Easy, Synapse

#136 Game Ball
  Game Ball/Readme.md
  Game Ball/index.html
  Game Ball/script.js
  Game Ball/style.css
Labels: Easy, Synapse

#140 Pizza ordering website with integrated chatbot
  pizza ordering chatbot and website/Final_project.html
  pizza ordering chatbot and website/Readme.md
Labels: Hard, Synapse

#144 ADDED A PROJECT
  ADVENTURE/1.jpg
  ADVENTURE/2.jpg
  ADVENTURE/3.jpg
  ADVENTURE/4.jpg
  ADVENTURE/5.jpg
  ADVENTURE/6.jpg
  ADVENTURE/7.jpg
  ADVENTURE/8.jpg
  ADVENTURE/9.jpg
  ADVENTURE/REDME.MD
  ADVENTURE/index.html
  ADVENTURE/style.css
Labels: Medium, Synapse

#143 Fighting Browser Game
  fighting-game-main/README.md
  fighting-game-main/data/background.png
  fighting-game-main/data/kenji/Attack1.png
  fighting-game-main/data/kenji/Attack2.png
  fighting-game-main/data/kenji/Death.png
  fighting-game-main/data/kenji/Fall.png
  fighting-game-main/data/kenji/Idle.png
  fighting-game-main/data/kenji/Jump.png
  fighting-game-main/data/kenji/Run.png
  fighting-game-main/data/kenji/Take hit.png
  fighting-game-main/data/samuraiMack/Attack1.png
  fighting-game-main/data/samuraiMack/Attack2.png
  fighting-game-main/data/samuraiMack/Death.png
  fighting-game-main/data/samuraiMack/Fall.png
  fighting-game-main/data/samuraiMack/Idle.png
  fighting-game-main/data/samuraiMack/Jump.png
  fighting-game-main/data/samuraiMack/Run.png
  fighting-game-main/data/samuraiMack/Take Hit - white silhouette.png
  fighting-game-main/data/samuraiMack/Take Hit.png
  fighting-game-main/data/shop.png
  fighting-game-main/index.html
  fighting-game-main/index.js
  fighting-game-main/js/classes.js
  fighting-game-main/js/utils.js
  space-game-main/README.md
  space-game-main/data/invader.png
  space-game-main/data/spaceship.png
  space-game-main/index.html
  space-game-main/index.js
Labels: Medium, Synapse

#142 Social Media Website with Theme Customization
  Social media website with theme Customization/README.md
  Social media website with theme Customization/images/feed-1.jpg
  Social media website with theme Customization/images/feed-2.jpg
  Social media website with theme Customization/images/feed-3.jpg
  Social media website with theme Customization/images/feed-4.jpg
  Social media website with theme Customization/images/feed-5.jpg
  Social media website with theme Customization/images/feed-6.jpg
  Social media website with theme Customization/images/feed-7.jpg
  Social media website with theme Customization/images/profile-1.jpg
  Social media website with theme Customization/images/profile-10.jpg
  Social media website with theme Customization/images/profile-11.jpg
  Social media website with theme Customization/images/profile-12.jpg
  Social media website with theme Customization/images/profile-13.jpg
  Social media website with theme Customization/images/profile-14.jpg
  Social media website with theme Customization/images/profile-15.jpg
  Social media website with theme Customization/images/profile-16.jpg
  Social media website with theme Customization/images/profile-17.jpg
  Social media website with theme Customization/images/profile-18.jpg
  Social media website with theme Customization/images/profile-19.jpg
  Social media website with theme Customization/images/profile-2.jpg
  Social media website with theme Customization/images/profile-20.jpg
  Social media website with theme Customization/images/profile-3.jpg
  Social media website with theme Customization/images/profile-4.jpg
  Social media website with theme Customization/images/profile-5.jpg
  Social media website with theme Customization/images/profile-6.jpg
  Social media website with theme Customization/images/profile-7.jpg
  Social media website with theme Customization/images/profile-8.jpg
  Social media website with theme Customization/images/profile-9.jpg
  Social media website with theme Customization/images/social logo.png
  Social media website with theme Customization/images/story-1.jpg
  Social media website with theme Customization/images/story-2.jpg
  Social media website with theme Customization/images/story-3.jpg
  Social media website with theme Customization/images/story-4.jpg
  Social media website with theme Customization/images/story-5.jpg
  Social media website with theme Customization/images/story-6.jpg
  Social media website with theme Customization/index.html
  Social media website with theme Customization/index.js
  Social media website with theme Customization/style.css
Labels: Synapse

#138 P-kart e-commerce
  P-kart e-commerce/README.md
  P-kart e-commerce/about.html
  P-kart e-commerce/buynow.html
  P-kart e-commerce/contact.html
  P-kart e-commerce/index.html
  P-kart e-commerce/sell.html
Labels: Easy, Synapse

#141 Ludo game with computer
  Ludo game with Computer/Readme.md
  Ludo game with Computer/index.html
  Ludo game with Computer/script.js
  Ludo game with Computer/style.css
Labels: Medium, Synapse

#139 Excel Website
  Excel Website/Readme.md
  Excel Website/formula.js
  Excel Website/fx.png
  Excel Website/index.html
  Excel Website/init.js
  Excel Website/menu.js
  Excel Website/nos.js
  Excel Website/sheets.js
  Excel Website/style.css
Labels: Hard, Synapse

#145 Twitter Clone
  Twitter Clone/README.md
  Twitter Clone/assets/Roboto-Regular.ttf
  Twitter Clone/css/all.css
  Twitter Clone/css/style.css
  Twitter Clone/img/content1.jpg
  Twitter Clone/img/content2.jpg
  Twitter Clone/img/content3.jpg
  Twitter Clone/img/content4.jpg
  Twitter Clone/img/content5.jpg
  Twitter Clone/img/profile.jpg
  Twitter Clone/img/profile1.jpg
  Twitter Clone/img/profile2.jpg
  Twitter Clone/img/profile3.jpg
  Twitter Clone/img/profile4.jpg
  Twitter Clone/img/user1.jpg
  Twitter Clone/img/user2.jpg
  Twitter Clone/img/user3.jpg
  Twitter Clone/img/user4.jpg
  Twitter Clone/img/user5.jpg
  Twitter Clone/img/user6.jpg
  Twitter Clone/img/user7.jpg
  Twitter Clone/img/user8.jpg
  Twitter Clone/index.html
  Twitter Clone/webfonts/fa-brands-400.eot
  Twitter Clone/webfonts/fa-brands-400.svg
  Twitter Clone/webfonts/fa-brands-400.ttf
  Twitter Clone/webfonts/fa-brands-400.woff
  Twitter Clone/webfonts/fa-brands-400.woff2
  Twitter Clone/webfonts/fa-regular-400.eot
  Twitter Clone/webfonts/fa-regular-400.svg
  Twitter Clone/webfonts/fa-regular-400.ttf
  Twitter Clone/webfonts/fa-regular-400.woff
  Twitter Clone/webfonts/fa-regular-400.woff2
  Twitter Clone/webfonts/fa-solid-900.eot
  Twitter Clone/webfonts/fa-solid-900.svg
  Twitter Clone/webfonts/fa-solid-900.ttf
  Twitter Clone/webfonts/fa-solid-900.woff
  Twitter Clone/webfonts/fa-solid-900.woff2
Labels: Easy, Synapse

#149 Doctor Appointment Website
  Doctor Appointment Website/Readme.md
  Doctor Appointment Website/about.css
  Doctor Appointment Website/about.html
  Doctor Appointment Website/doctors.css
  Doctor Appointment Website/doctors.html
  Doctor Appointment Website/index.html
  Doctor Appointment Website/script.js
  Doctor Appointment Website/style.css
Labels: Medium, Synapse

#147 Covid-Awareness-Website
  BACKGROUND-GENERATOR/README.md
  BACKGROUND-GENERATOR/bg-generator.html
  BACKGROUND-GENERATOR/index.html
  BACKGROUND-GENERATOR/style.css
  BACKGROUND-GENERATOR/style2.css
  COVID-AWARENESS-WEBSITE/README.md
  COVID-AWARENESS-WEBSITE/bootstrap.min.css
  COVID-AWARENESS-WEBSITE/index.html
  COVID-AWARENESS-WEBSITE/main.css
  COVID-AWARENESS-WEBSITE/page2.css
  RESTAURANT_WEBSITE/README.md
  RESTAURANT_WEBSITE/gitignore
  RESTAURANT_WEBSITE/index.html
  RESTAURANT_WEBSITE/style.css
Labels: Medium, Synapse

#148 add Login Card
  Login_Card/Readme.md
  Login_Card/Readme.txt
  Login_Card/image/Daco_4184671.png
  Login_Card/image/—Pngtree—initial s mono line logo_5181400.png
  Login_Card/login_p1.html
  Login_Card/login_style.css
  Login_Card/login_style.css.map
  Login_Card/login_style.scss
Labels: Medium, Synapse

#150 Pro-Coder
  Pro-coder/README.md
  Pro-coder/about.html
  Pro-coder/contact.html
  Pro-coder/index.html
Labels: Easy, Synapse

#155 1st-commit-(hospital website)
  Hospital-Website/README.md
  Hospital-Website/css/style.css
  Hospital-Website/image/about-img.svg
  Hospital-Website/image/blog-1.jpg
  Hospital-Website/image/blog-2.jpg
  Hospital-Website/image/blog-3.jpg
  Hospital-Website/image/book-img.svg
  Hospital-Website/image/doc-1.jpg
  Hospital-Website/image/doc-2.jpg
  Hospital-Website/image/doc-3.jpg
  Hospital-Website/image/doc-4.jpg
  Hospital-Website/image/doc-5.jpg
  Hospital-Website/image/doc-6.jpg
  Hospital-Website/image/home-img.svg
  Hospital-Website/image/pic-1.png
  Hospital-Website/image/pic-2.png
  Hospital-Website/image/pic-3.png
  Hospital-Website/index.html
  Hospital-Website/js/script.js
Labels: Hard, Synapse

#153 News Homepage
  News-Homepage/README.md
  News-Homepage/assets/fonts/Inter-VariableFont_slnt,wght.ttf
  News-Homepage/assets/fonts/README.txt
  News-Homepage/assets/fonts/static/Inter-Bold.ttf
  News-Homepage/assets/fonts/static/Inter-ExtraBold.ttf
  News-Homepage/assets/fonts/static/Inter-Regular.ttf
  News-Homepage/assets/images/favicon-32x32.png
  News-Homepage/assets/images/icon-menu-close.svg
  News-Homepage/assets/images/icon-menu.svg
  News-Homepage/assets/images/image-gaming-growth.jpg
  News-Homepage/assets/images/image-retro-pcs.jpg
  News-Homepage/assets/images/image-top-laptops.jpg
  News-Homepage/assets/images/image-web-3-desktop.jpg
  News-Homepage/assets/images/image-web-3-mobile.jpg
  News-Homepage/assets/images/logo.svg
  News-Homepage/final/mobile.png
  News-Homepage/final/ticket.png
  News-Homepage/final/wide.png
  News-Homepage/index.html
  News-Homepage/index.js
  News-Homepage/style.css
Labels: Easy, Synapse

#156 1st-commit(burger website)
  Burger-website/README.md
  Burger-website/css/style.css
  Burger-website/css/style.scss
  Burger-website/images/about-img.png
  Burger-website/images/background.jpg
  Burger-website/images/blog-1.jpg
  Burger-website/images/blog-2.jpg
  Burger-website/images/blog-3.jpg
  Burger-website/images/burger-baner.png
  Burger-website/images/home-bg.png
  Burger-website/images/logo.png
  Burger-website/images/pic-1.png
  Burger-website/images/pic-2.png
  Burger-website/images/pic-3.png
  Burger-website/images/product-1.png
  Burger-website/images/product-2.png
  Burger-website/images/product-3.png
  Burger-website/images/product-4.png
  Burger-website/images/product-5.png
  Burger-website/images/product-6.png
  Burger-website/images/title-img.png
  Burger-website/index.html
  Burger-website/js/script.js
Labels: Hard, Synapse

#157 web development commit
  Furniture website - DB/furniture website/README.md
  Furniture website - DB/furniture website/about.html
  Furniture website - DB/furniture website/blog.html
  Furniture website - DB/furniture website/contact.html
  Furniture website - DB/furniture website/css/style.css
  Furniture website - DB/furniture website/css/style.scss
  Furniture website - DB/furniture website/home.html
  Furniture website - DB/furniture website/image/about-img.jpg
  Furniture website - DB/furniture website/image/banner-1.jpg
  Furniture website - DB/furniture website/image/banner-2.jpg
  Furniture website - DB/furniture website/image/banner-3.jpg
  Furniture website - DB/furniture website/image/blog-1.jpg
  Furniture website - DB/furniture website/image/blog-2.jpg
  Furniture website - DB/furniture website/image/blog-3.jpg
  Furniture website - DB/furniture website/image/blog-4.jpg
  Furniture website - DB/furniture website/image/blog-5.jpg
  Furniture website - DB/furniture website/image/blog-6.jpg
  Furniture website - DB/furniture website/image/cart-img-1.jpg
  Furniture website - DB/furniture website/image/cart-img-2.jpg
  Furniture website - DB/furniture website/image/cart-img-3.jpg
  Furniture website - DB/furniture website/image/cart-img-4.jpg
  Furniture website - DB/furniture website/image/home-img-1.png
  Furniture website - DB/furniture website/image/home-img-2.png
  Furniture website - DB/furniture website/image/icon-1.png
  Furniture website - DB/furniture website/image/icon-2.png
  Furniture website - DB/furniture website/image/icon-3.png
  Furniture website - DB/furniture website/image/icon-4.png
  Furniture website - DB/furniture website/image/icon-5.png
  Furniture website - DB/furniture website/image/product-1.jpg
  Furniture website - DB/furniture website/image/product-2.jpg
  Furniture website - DB/furniture website/image/product-3.jpg
  Furniture website - DB/furniture website/image/product-4.jpg
  Furniture website - DB/furniture website/image/product-5.jpg
  Furniture website - DB/furniture website/image/product-6.jpg
  Furniture website - DB/furniture website/image/product-7.jpg
  Furniture website - DB/furniture website/image/product-8.jpg
  Furniture website - DB/furniture website/image/serv-1.svg
  Furniture website - DB/furniture website/image/serv-2.svg
  Furniture website - DB/furniture website/image/serv-3.svg
  Furniture website - DB/furniture website/image/team-1.jpg
  Furniture website - DB/furniture website/image/team-2.jpg
  Furniture website - DB/furniture website/image/team-3.jpg
  Furniture website - DB/furniture website/image/team-4.jpg
  Furniture website - DB/furniture website/image/team-5.jpg
  Furniture website - DB/furniture website/image/team-6.jpg
  Furniture website - DB/furniture website/script.js
  Furniture website - DB/furniture website/shop.html
  Furniture website - DB/furniture website/team.html
Labels: Medium, Synapse

#159 Load Runner
  Load Runner/Readme.md
  Load Runner/index.html
  Load Runner/script.js
  Load Runner/style.css
  Mage Game/Readme.md
Labels: Medium, Synapse

#160 add card style
  card_style/Readme.md
  card_style/card.html
  card_style/image/k.iit.jpg
  card_style/style.css
Labels: Easy, Synapse

#162 add analog clock
  clock_analog/Readme.md
  clock_analog/clock.html
  clock_analog/style.css
Labels: Easy, Synapse

#163 add responsive website
  PROJECT AISHYAM WEBSITE/Readme.md
  PROJECT AISHYAM WEBSITE/images/banner.jpg
  PROJECT AISHYAM WEBSITE/images/profile-1.JPEG
  PROJECT AISHYAM WEBSITE/script.js
  PROJECT AISHYAM WEBSITE/style.css
  PROJECT AISHYAM WEBSITE/test1.html
Labels: Medium, Synapse

#161 Discord Music Bot
  discord music bot/Dockerfile
  discord music bot/api/Middlewares/Auth.js
  discord music bot/api/Routes/user.js
  discord music bot/api/index.js
  discord music bot/api/routes.js
  discord music bot/api/socket/index.js
  discord music bot/app.json
  discord music bot/botconfig.js
  discord music bot/commands/bassboost.js
  discord music bot/commands/clear.js
  discord music bot/commands/config.js
  discord music bot/commands/disconnect.js
  discord music bot/commands/grab.js
  discord music bot/commands/help.js
  discord music bot/commands/invite.js
  discord music bot/commands/loop.js
  discord music bot/commands/loopqueue.js
  discord music bot/commands/lyrics.js
  discord music bot/commands/move.js
  discord music bot/commands/nowplaying.js
  discord music bot/commands/pause.js
  discord music bot/commands/play.js
  discord music bot/commands/queue.js
  discord music bot/commands/remove.js
  discord music bot/commands/resume.js
  discord music bot/commands/search.js
  discord music bot/commands/seek.js
  discord music bot/commands/shuffle.js
  discord music bot/commands/skip.js
  discord music bot/commands/skipto.js
  discord music bot/commands/stats.js
  discord music bot/commands/volume.js
  discord music bot/commands/youtube.js
  discord music bot/docker/application.yml
  discord music bot/events/guildCreate.js
  discord music bot/events/message.js
  discord music bot/events/raw.js
  discord music bot/events/ready.js
  discord music bot/events/voiceStateUpdate.js
  discord music bot/index.js
  discord music bot/structures/DiscordMusicBot.js
  discord music bot/structures/EpicPlayer.js
  discord music bot/structures/Logger.js
  discord music bot/util/ProgressBar.js
  discord music bot/util/RegisterSlashCommands.js
  discord music bot/util/TimeString.js
  discord music bot/util/pagination.js
Labels: Hard, Synapse

#164 add fluid-gallery
  fluid-gallery/Font-Awesome-4.7/CONTRIBUTING.md
  fluid-gallery/Font-Awesome-4.7/HELP-US-OUT.txt
  fluid-gallery/Font-Awesome-4.7/README.md
  fluid-gallery/Font-Awesome-4.7/css/font-awesome.min.css
  fluid-gallery/Font-Awesome-4.7/fonts/FontAwesome.otf
  fluid-gallery/Font-Awesome-4.7/fonts/fontawesome-webfont.eot
  fluid-gallery/Font-Awesome-4.7/fonts/fontawesome-webfont.svg
  fluid-gallery/Font-Awesome-4.7/fonts/fontawesome-webfont.ttf
  fluid-gallery/Font-Awesome-4.7/fonts/fontawesome-webfont.woff
  fluid-gallery/Font-Awesome-4.7/fonts/fontawesome-webfont.woff2
  fluid-gallery/Readme.md
  fluid-gallery/css/bootstrap.min.css
  fluid-gallery/css/hero-slider-style.css
  fluid-gallery/css/magnific-popup.css
  fluid-gallery/css/templatemo-style.css
  fluid-gallery/img/tm-img-01-tn.jpg
  fluid-gallery/img/tm-img-01.jpg
  fluid-gallery/img/tm-img-02-tn.jpg
  fluid-gallery/img/tm-img-02.jpg
  fluid-gallery/img/tm-img-03-tn.jpg
  fluid-gallery/img/tm-img-03.jpg
  fluid-gallery/img/tm-img-04-tn.jpg
  fluid-gallery/img/tm-img-04.jpg
  fluid-gallery/img/tm-img-05-tn.jpg
  fluid-gallery/img/tm-img-05.jpg
  fluid-gallery/img/tm-img-06-tn.jpg
  fluid-gallery/img/tm-img-06.jpg
  fluid-gallery/img/tm-img-07-tn.jpg
  fluid-gallery/img/tm-img-07.jpg
  fluid-gallery/img/tm-img-08-tn.jpg
  fluid-gallery/img/tm-img-08.jpg
  fluid-gallery/img/tm-img-09-tn.jpg
  fluid-gallery/img/tm-img-09.jpg
  fluid-gallery/img/tm-img-10-tn.jpg
  fluid-gallery/img/tm-img-10.jpg
  fluid-gallery/img/tm-img-11-tn.jpg
  fluid-gallery/img/tm-img-11.jpg
  fluid-gallery/img/tm-img-12-tn.jpg
  fluid-gallery/img/tm-img-12.jpg
  fluid-gallery/img/tm-img-13-tn.jpg
  fluid-gallery/img/tm-img-13.jpg
  fluid-gallery/img/tm-img-14-tn.jpg
  fluid-gallery/img/tm-img-14.jpg
  fluid-gallery/img/tm-img-15-tn.jpg
  fluid-gallery/img/tm-img-15.jpg
  fluid-gallery/img/tm-img-16-tn.jpg
  fluid-gallery/img/tm-img-16.jpg
  fluid-gallery/index-color.html
  fluid-gallery/index-gray.html
  fluid-gallery/index.html
  fluid-gallery/js/bootstrap.min.js
  fluid-gallery/js/hero-slider-main.js
  fluid-gallery/js/jquery-1.11.3.min.js
  fluid-gallery/js/jquery.magnific-popup.min.js
  fluid-gallery/js/tether-LICENSE
  fluid-gallery/js/tether.min.js
Labels: Medium, Synapse

#168 My portfolio website
  portfolio Website/assets/css/styles.css
  portfolio Website/assets/img/favicon-16x16.png
  portfolio Website/assets/img/favicon.png
  portfolio Website/assets/img/p1.png
  portfolio Website/assets/img/p2.png
  portfolio Website/assets/img/perfil.png
  portfolio Website/assets/img/profile-pic.png
  portfolio Website/assets/js/main.js
  portfolio Website/assets/js/scrollreveal.min.js
  portfolio Website/assets/pdf/Gianell-Cv.pdf
  portfolio Website/assets/scss/base/_base.scss
  portfolio Website/assets/scss/components/_breakpoints.scss
  portfolio Website/assets/scss/components/_button.scss
  portfolio Website/assets/scss/components/_filters.scss
  portfolio Website/assets/scss/components/_footer.scss
  portfolio Website/assets/scss/components/_profile.scss
  portfolio Website/assets/scss/components/_scroll.scss
  portfolio Website/assets/scss/config/_variables.scss
  portfolio Website/assets/scss/layout/_layout.scss
  portfolio Website/assets/scss/styles.scss
  portfolio Website/assets/scss/theme/_theme.scss
  portfolio Website/button contact home.png
  portfolio Website/index.html
  portfolio Website/readme.md
Labels: Medium, Synapse

#167 add Pacman-clone
  pacman-clone/Readme.md
  pacman-clone/data/db-handler.php
  pacman-clone/data/map.json
  pacman-clone/fonts/PressStart2Play.eot
  pacman-clone/fonts/PressStart2Play.ttf
  pacman-clone/fonts/PressStart2Play.woff
  pacman-clone/img/Icon-106x106.png
  pacman-clone/img/Icon-130x130.png
  pacman-clone/img/Icon-150x130.png
  pacman-clone/img/Icon-200x200.png
  pacman-clone/img/Icon-300x300.png
  pacman-clone/img/Icon-32x32.png
  pacman-clone/img/Icon-512x512.png
  pacman-clone/img/Pacman-Icon.svg
  pacman-clone/img/audio-icon-mute.png
  pacman-clone/img/audio-icon.png
  pacman-clone/img/bg-pattern-black.png
  pacman-clone/img/blinky.svg
  pacman-clone/img/clyde.svg
  pacman-clone/img/dazzled.svg
  pacman-clone/img/dazzled2.svg
  pacman-clone/img/dead.svg
  pacman-clone/img/heart.png
  pacman-clone/img/icon-128.png
  pacman-clone/img/icon-128_old.png
  pacman-clone/img/inky.svg
  pacman-clone/img/instructions/instructions_chase.PNG
  pacman-clone/img/instructions/instructions_powerpill.PNG
  pacman-clone/img/instructions/instructions_scatter.PNG
  pacman-clone/img/pinky.svg
  pacman-clone/img/platzh1rsch-logo.png
  pacman-clone/index.htm
  pacman-clone/js/jquery-1.10.2.min.js
  pacman-clone/js/jquery.hammer.min.js
  pacman-clone/js/pacman/ghost.js
  pacman-clone/js/pacman/pacman.js
  pacman-clone/js/virtualjoystick.js
  pacman-clone/manifest.json
  pacman-clone/mp3/die.mp3
  pacman-clone/mp3/eatghost.mp3
  pacman-clone/mp3/powerpill.mp3
  pacman-clone/mp3/theme.mp3
  pacman-clone/mp3/waka.mp3
  pacman-clone/package-lock.json
  pacman-clone/package.json
  pacman-clone/pacman-canvas.css
  pacman-clone/pacman-canvas.js
  pacman-clone/pacman-canvas.test.js
  pacman-clone/server.js
  pacman-clone/style.css
  pacman-clone/wav/die.wav
  pacman-clone/wav/eatghost.wav
  pacman-clone/wav/powerpill.wav
  pacman-clone/wav/theme.wav
  pacman-clone/wav/waka.wav
  pacman-clone/web-app-manifest.json
  pacman-clone/webpack.config.js
Labels: Medium, Synapse

#166 Online Restaurants
  online Resturant/README.md
  online Resturant/assets/css/styles.css
  online Resturant/assets/img/about.jpg
  online Resturant/assets/img/app1.png
  online Resturant/assets/img/app2.png
  online Resturant/assets/img/dish.svg
  online Resturant/assets/img/home.png
  online Resturant/assets/img/movil-app.png
  online Resturant/assets/img/pizza.svg
  online Resturant/assets/img/plate1.png
  online Resturant/assets/img/plate2.png
  online Resturant/assets/img/plate3.png
  online Resturant/assets/img/truck.svg
  online Resturant/assets/js/main.js
  online Resturant/assets/scss/styles.scss
  online Resturant/index.html
Labels: Medium, Synapse

#170 add Snake-game
  snake_game/Readme.md
  snake_game/snakegame.html
Labels: Medium, Synapse

#172 1st-commit-(hotel-booking)
  Hotel-Booking-Website/.vscode/settings.json
  Hotel-Booking-Website/README.md
  Hotel-Booking-Website/css/style.css
  Hotel-Booking-Website/images/about-img-1.jpg
  Hotel-Booking-Website/images/about-img-2.jpg
  Hotel-Booking-Website/images/about-img-3.jpg
  Hotel-Booking-Website/images/gallery-img-1.jpg
  Hotel-Booking-Website/images/gallery-img-2.webp
  Hotel-Booking-Website/images/gallery-img-3.webp
  Hotel-Booking-Website/images/gallery-img-4.webp
  Hotel-Booking-Website/images/gallery-img-5.webp
  Hotel-Booking-Website/images/gallery-img-6.webp
  Hotel-Booking-Website/images/home-img-1.jpg
  Hotel-Booking-Website/images/home-img-2.jpg
  Hotel-Booking-Website/images/home-img-3.jpg
  Hotel-Booking-Website/images/icon-1.png
  Hotel-Booking-Website/images/icon-2.png
  Hotel-Booking-Website/images/icon-3.png
  Hotel-Booking-Website/images/icon-4.png
  Hotel-Booking-Website/images/icon-5.png
  Hotel-Booking-Website/images/icon-6.png
  Hotel-Booking-Website/images/pic-1.png
  Hotel-Booking-Website/images/pic-2.png
  Hotel-Booking-Website/images/pic-3.png
  Hotel-Booking-Website/images/pic-4.png
  Hotel-Booking-Website/images/pic-5.png
  Hotel-Booking-Website/images/pic-6.png
  Hotel-Booking-Website/index.html
  Hotel-Booking-Website/js/script.js
Labels: Medium, Synapse
